package main

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
)

func TestFindTestsInPackages(t *testing.T) {
	const d = "./internal/testmodule"
	dir, err := filepath.Abs(d)
	if err != nil {
		t.Fatal(err)
	}

	absPath := func(p string) string {
		abs, err := filepath.Abs(filepath.Join(dir, p))
		if err != nil {
			t.Fatalf("%q: %v", p, err)
		}
		return abs
	}

	logfn := func(string, ...any) {}
	got, err := findTestsInPackages(
		t.Context(),
		"./internal/testmodule",
		[]string{"./..."},
		nil,
		logfn,
	)
	if err != nil {
		t.Fatalf("find-tests-in-packages: %v", err)
	}

	want := []*TestInfo{
		{
			Name:            "TestSimple",
			FullName:        "TestSimple",
			FullDisplayName: "TestSimple",
			DisplayName:     "TestSimple",
			Package:         "testmodule",
			Directory:       dir,
			File:            absPath("/some_test.go"),
			Range: SourceRange{
				Start: SourcePosition{Line: 8, Column: 6},
				End:   SourcePosition{Line: 10, Column: 2},
			},
		},
		{
			Name:            "TestSubTests",
			DisplayName:     "TestSubTests",
			FullName:        "TestSubTests",
			FullDisplayName: "TestSubTests",
			Package:         "testmodule",
			Directory:       dir,
			File:            absPath("/some_test.go"),
			Range: SourceRange{
				Start: SourcePosition{Line: 12, Column: 6},
				End:   SourcePosition{Line: 19, Column: 2},
			},
			SubTests: []*TestInfo{
				{
					Name:            "t1",
					DisplayName:     "t1",
					FullName:        "TestSubTests/t1",
					FullDisplayName: "TestSubTests/t1",
					Package:         "testmodule",
					Directory:       dir,
					File:            absPath("/some_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 13, Column: 2},
						End:   SourcePosition{Line: 15, Column: 4},
					},
					IsSubtest: true,
				},
				{
					Name:            "t2",
					DisplayName:     "t2",
					FullName:        "TestSubTests/t2",
					FullDisplayName: "TestSubTests/t2",
					Package:         "testmodule",
					Directory:       dir,
					File:            absPath("/some_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 16, Column: 2},
						End:   SourcePosition{Line: 18, Column: 4},
					},
					IsSubtest: true,
				},
			},
		},
		{
			Name:            "TestNestedSubTests",
			DisplayName:     "TestNestedSubTests",
			FullName:        "TestNestedSubTests",
			FullDisplayName: "TestNestedSubTests",
			Package:         "testmodule",
			Directory:       dir,
			File:            absPath("/some_test.go"),
			Range: SourceRange{
				Start: SourcePosition{Line: 21, Column: 6},
				End:   SourcePosition{Line: 27, Column: 2},
			},
			SubTests: []*TestInfo{{
				Name:            "t1",
				DisplayName:     "t1",
				FullName:        "TestNestedSubTests/t1",
				FullDisplayName: "TestNestedSubTests/t1",
				Package:         "testmodule",
				Directory:       dir,
				File:            absPath("/some_test.go"),
				Range: SourceRange{
					Start: SourcePosition{Line: 22, Column: 2},
					End:   SourcePosition{Line: 26, Column: 4},
				},
				IsSubtest: true,
				SubTests: []*TestInfo{{
					Name:            "t1",
					DisplayName:     "t1",
					FullName:        "TestNestedSubTests/t1/t1",
					FullDisplayName: "TestNestedSubTests/t1/t1",
					Package:         "testmodule",
					Directory:       dir,
					File:            absPath("/some_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 23, Column: 3},
						End:   SourcePosition{Line: 25, Column: 5},
					},
					IsSubtest: true,
				}},
			}},
		},
		{
			Name:            "TestSubTestsWithGeneratedNames",
			DisplayName:     "TestSubTestsWithGeneratedNames",
			FullName:        "TestSubTestsWithGeneratedNames",
			FullDisplayName: "TestSubTestsWithGeneratedNames",
			Package:         "testmodule",
			Directory:       dir,
			File:            absPath("/some_test.go"),
			Range: SourceRange{
				Start: SourcePosition{Line: 29, Column: 6},
				End:   SourcePosition{Line: 35, Column: 2},
			},
			SubTests: []*TestInfo{{
				Name:            `<fmt.Sprintf("t%v", i)>`,
				DisplayName:     `<fmt.Sprintf("t%v", i)>`,
				FullName:        `TestSubTestsWithGeneratedNames/<fmt.Sprintf("t%v", i)>`,
				FullDisplayName: `TestSubTestsWithGeneratedNames/<fmt.Sprintf("t%v", i)>`,
				Package:         "testmodule",
				Directory:       dir,
				File:            absPath("/some_test.go"),
				Range: SourceRange{
					Start: SourcePosition{Line: 31, Column: 3},
					End:   SourcePosition{Line: 33, Column: 5},
				},
				HasGeneratedName: true,
				IsSubtest:        true,
			}},
		},
		{
			Name:            "TestTable",
			DisplayName:     "TestTable",
			FullName:        "TestTable",
			FullDisplayName: "TestTable",
			Package:         "testmodule",
			Directory:       dir,
			File:            absPath("/some_test.go"),
			Range: SourceRange{
				Start: SourcePosition{Line: 37, Column: 6},
				End:   SourcePosition{Line: 52, Column: 2},
			},
			SubTests: []*TestInfo{
				{
					Name:            "t1",
					DisplayName:     "t1",
					FullName:        "TestTable/t1",
					FullDisplayName: "TestTable/t1",
					Package:         "testmodule",
					Directory:       dir,
					File:            absPath("/some_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 43, Column: 3},
						End:   SourcePosition{Line: 43, Column: 43},
					},
					HasGeneratedName: false,
					IsSubtest:        true,
				},
				{
					Name:            "t2",
					DisplayName:     "t2",
					FullName:        "TestTable/t2",
					FullDisplayName: "TestTable/t2",
					Package:         "testmodule",
					Directory:       dir,
					File:            absPath("/some_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 44, Column: 3},
						End:   SourcePosition{Line: 44, Column: 43},
					},
					HasGeneratedName: false,
					IsSubtest:        true,
				},
			},
		},
		{
			Name:            "TestTableTestWithinSubTest",
			DisplayName:     "TestTableTestWithinSubTest",
			FullName:        "TestTableTestWithinSubTest",
			FullDisplayName: "TestTableTestWithinSubTest",
			Package:         "testmodule",
			Directory:       dir,
			File:            absPath("/some_test.go"),
			Range: SourceRange{
				Start: SourcePosition{Line: 54, Column: 6},
				End:   SourcePosition{Line: 88, Column: 2},
			},
			SubTests: []*TestInfo{
				{
					Name:            "s1",
					DisplayName:     "s1",
					FullName:        "TestTableTestWithinSubTest/s1",
					FullDisplayName: "TestTableTestWithinSubTest/s1",
					Package:         "testmodule",
					Directory:       dir,
					File:            absPath("/some_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 55, Column: 2},
						End:   SourcePosition{Line: 70, Column: 4},
					},
					IsSubtest: true,
					SubTests: []*TestInfo{
						{
							Name:            "t1",
							DisplayName:     "t1",
							FullName:        "TestTableTestWithinSubTest/s1/t1",
							FullDisplayName: "TestTableTestWithinSubTest/s1/t1",
							Package:         "testmodule",
							Directory:       dir,
							File:            absPath("/some_test.go"),
							Range: SourceRange{
								Start: SourcePosition{Line: 61, Column: 4},
								End:   SourcePosition{Line: 61, Column: 44},
							},
							IsSubtest: true,
						},
						{
							Name:            "t2",
							DisplayName:     "t2",
							FullName:        "TestTableTestWithinSubTest/s1/t2",
							FullDisplayName: "TestTableTestWithinSubTest/s1/t2",
							Package:         "testmodule",
							Directory:       dir,
							File:            absPath("/some_test.go"),
							Range: SourceRange{
								Start: SourcePosition{Line: 62, Column: 4},
								End:   SourcePosition{Line: 62, Column: 44},
							},
							IsSubtest: true,
						},
					},
				},
				{
					Name:            "s2",
					DisplayName:     "s2",
					FullName:        "TestTableTestWithinSubTest/s2",
					FullDisplayName: "TestTableTestWithinSubTest/s2",
					Package:         "testmodule",
					Directory:       dir,
					File:            absPath("/some_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 72, Column: 2},
						End:   SourcePosition{Line: 87, Column: 4},
					},
					IsSubtest: true,
					SubTests: []*TestInfo{
						{
							Name:            "t1",
							DisplayName:     "t1",
							FullName:        "TestTableTestWithinSubTest/s2/t1",
							FullDisplayName: "TestTableTestWithinSubTest/s2/t1",
							Package:         "testmodule",
							Directory:       dir,
							File:            absPath("/some_test.go"),
							Range: SourceRange{
								Start: SourcePosition{Line: 78, Column: 4},
								End:   SourcePosition{Line: 78, Column: 44},
							},
							IsSubtest: true,
						},
						{
							Name:            "t2",
							DisplayName:     "t2",
							FullName:        "TestTableTestWithinSubTest/s2/t2",
							FullDisplayName: "TestTableTestWithinSubTest/s2/t2",
							Package:         "testmodule",
							Directory:       dir,
							File:            absPath("/some_test.go"),
							Range: SourceRange{
								Start: SourcePosition{Line: 79, Column: 4},
								End:   SourcePosition{Line: 79, Column: 44},
							},
							IsSubtest: true,
						},
					},
				},
			},
		},
		{
			Name:            "TestTableTestsWithinSubTestsWithPositionals",
			DisplayName:     "TestTableTestsWithinSubTestsWithPositionals",
			FullName:        "TestTableTestsWithinSubTestsWithPositionals",
			FullDisplayName: "TestTableTestsWithinSubTestsWithPositionals",
			Package:         "testmodule",
			Directory:       dir,
			File:            absPath("/some_test.go"),
			Range: SourceRange{
				Start: SourcePosition{Line: 90, Column: 6},
				End:   SourcePosition{Line: 120, Column: 2},
			},
			SubTests: []*TestInfo{
				{
					Name:            "t1",
					DisplayName:     "t1",
					FullName:        "TestTableTestsWithinSubTestsWithPositionals/t1",
					FullDisplayName: "TestTableTestsWithinSubTestsWithPositionals/t1",
					Package:         "testmodule",
					Directory:       dir,
					File:            absPath("/some_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 91, Column: 2},
						End:   SourcePosition{Line: 104, Column: 4},
					},
					IsSubtest: true,
					SubTests: []*TestInfo{
						{
							Name:            "tt1",
							DisplayName:     "tt1",
							FullName:        "TestTableTestsWithinSubTestsWithPositionals/t1/tt1",
							FullDisplayName: "TestTableTestsWithinSubTestsWithPositionals/t1/tt1",
							Package:         "testmodule",
							Directory:       dir,
							File:            absPath("/some_test.go"),
							Range: SourceRange{
								Start: SourcePosition{Line: 96, Column: 4},
								End:   SourcePosition{Line: 96, Column: 18},
							},
							IsSubtest: true,
						},
						{
							Name:            "tt2 with space",
							DisplayName:     "tt2_with_space",
							FullName:        "TestTableTestsWithinSubTestsWithPositionals/t1/tt2 with space",
							FullDisplayName: "TestTableTestsWithinSubTestsWithPositionals/t1/tt2_with_space",
							Package:         "testmodule",
							Directory:       dir,
							File:            absPath("/some_test.go"),
							Range: SourceRange{
								Start: SourcePosition{Line: 97, Column: 4},
								End:   SourcePosition{Line: 97, Column: 40},
							},
							IsSubtest: true,
						},
					},
				},
				{
					Name:            "t2",
					DisplayName:     "t2",
					FullName:        "TestTableTestsWithinSubTestsWithPositionals/t2",
					FullDisplayName: "TestTableTestsWithinSubTestsWithPositionals/t2",
					Package:         "testmodule",
					Directory:       dir,
					File:            absPath("/some_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 106, Column: 2},
						End:   SourcePosition{Line: 119, Column: 4},
					},
					IsSubtest: true,
					SubTests: []*TestInfo{
						{
							Name:            "tt1",
							DisplayName:     "tt1",
							FullName:        "TestTableTestsWithinSubTestsWithPositionals/t2/tt1",
							FullDisplayName: "TestTableTestsWithinSubTestsWithPositionals/t2/tt1",
							Package:         "testmodule",
							Directory:       dir,
							File:            absPath("/some_test.go"),
							Range: SourceRange{
								Start: SourcePosition{Line: 111, Column: 4},
								End:   SourcePosition{Line: 111, Column: 18},
							},
							IsSubtest: true,
						},
						{
							Name:            "tt2 with space",
							DisplayName:     "tt2_with_space",
							FullName:        "TestTableTestsWithinSubTestsWithPositionals/t2/tt2 with space",
							FullDisplayName: "TestTableTestsWithinSubTestsWithPositionals/t2/tt2_with_space",
							Package:         "testmodule",
							Directory:       dir,
							File:            absPath("/some_test.go"),
							Range: SourceRange{
								Start: SourcePosition{Line: 112, Column: 4},
								End:   SourcePosition{Line: 112, Column: 40},
							},
							IsSubtest: true,
						},
					},
				},
			},
		},
		{
			Name:            "TestSimple",
			DisplayName:     "TestSimple",
			FullName:        "TestSimple",
			FullDisplayName: "TestSimple",
			Package:         "subpkg",
			Directory:       absPath("/subpkg"),
			File:            absPath("subpkg/subpkg_test.go"),
			Range: SourceRange{
				Start: SourcePosition{Line: 8, Column: 6},
				End:   SourcePosition{Line: 10, Column: 2},
			},
		},
		{
			Name:            "TestSubTests",
			DisplayName:     "TestSubTests",
			FullName:        "TestSubTests",
			FullDisplayName: "TestSubTests",
			Package:         "subpkg",
			Directory:       absPath("/subpkg"),
			File:            absPath("subpkg/subpkg_test.go"),
			Range: SourceRange{
				Start: SourcePosition{Line: 12, Column: 6},
				End:   SourcePosition{Line: 19, Column: 2},
			},
			SubTests: []*TestInfo{
				{
					Name:            "t1",
					DisplayName:     "t1",
					FullName:        "TestSubTests/t1",
					FullDisplayName: "TestSubTests/t1",
					Package:         "subpkg",
					Directory:       absPath("/subpkg"),
					File:            absPath("subpkg/subpkg_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 13, Column: 2},
						End:   SourcePosition{Line: 15, Column: 4},
					},
					IsSubtest: true,
				},
				{
					Name:            "t2",
					DisplayName:     "t2",
					FullName:        "TestSubTests/t2",
					FullDisplayName: "TestSubTests/t2",
					Package:         "subpkg",
					Directory:       absPath("/subpkg"),
					File:            absPath("subpkg/subpkg_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 16, Column: 2},
						End:   SourcePosition{Line: 18, Column: 4},
					},
					IsSubtest: true,
				},
			},
		},
		{
			Name:            "TestNestedSubTests",
			DisplayName:     "TestNestedSubTests",
			FullName:        "TestNestedSubTests",
			FullDisplayName: "TestNestedSubTests",
			Package:         "subpkg",
			Directory:       absPath("/subpkg"),
			File:            absPath("subpkg/subpkg_test.go"),
			Range: SourceRange{
				Start: SourcePosition{Line: 21, Column: 6},
				End:   SourcePosition{Line: 27, Column: 2},
			},
			SubTests: []*TestInfo{{
				Name:            "t1",
				DisplayName:     "t1",
				FullName:        "TestNestedSubTests/t1",
				FullDisplayName: "TestNestedSubTests/t1",
				Package:         "subpkg",
				Directory:       absPath("/subpkg"),
				File:            absPath("subpkg/subpkg_test.go"),
				Range: SourceRange{
					Start: SourcePosition{Line: 22, Column: 2},
					End:   SourcePosition{Line: 26, Column: 4},
				},
				IsSubtest: true,
				SubTests: []*TestInfo{{
					Name:            "t1",
					DisplayName:     "t1",
					FullName:        "TestNestedSubTests/t1/t1",
					FullDisplayName: "TestNestedSubTests/t1/t1",
					Package:         "subpkg",
					Directory:       absPath("/subpkg"),
					File:            absPath("subpkg/subpkg_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 23, Column: 3},
						End:   SourcePosition{Line: 25, Column: 5},
					},
					IsSubtest: true,
				}},
			}},
		},
		{
			Name:            "TestSubTestsWithGeneratedNames",
			DisplayName:     "TestSubTestsWithGeneratedNames",
			FullName:        "TestSubTestsWithGeneratedNames",
			FullDisplayName: "TestSubTestsWithGeneratedNames",
			Package:         "subpkg",
			Directory:       absPath("/subpkg"),
			File:            absPath("subpkg/subpkg_test.go"),
			Range: SourceRange{
				Start: SourcePosition{Line: 29, Column: 6},
				End:   SourcePosition{Line: 35, Column: 2},
			},
			SubTests: []*TestInfo{{
				Name:            `<fmt.Sprintf("t%v", i)>`,
				DisplayName:     `<fmt.Sprintf("t%v", i)>`,
				FullName:        `TestSubTestsWithGeneratedNames/<fmt.Sprintf("t%v", i)>`,
				FullDisplayName: `TestSubTestsWithGeneratedNames/<fmt.Sprintf("t%v", i)>`,
				Package:         "subpkg",
				Directory:       absPath("/subpkg"),
				File:            absPath("subpkg/subpkg_test.go"),
				Range: SourceRange{
					Start: SourcePosition{Line: 31, Column: 3},
					End:   SourcePosition{Line: 33, Column: 5},
				},
				HasGeneratedName: true,
				IsSubtest:        true,
			}},
		},
		{
			Name:            "TestTable",
			DisplayName:     "TestTable",
			FullName:        "TestTable",
			FullDisplayName: "TestTable",
			Package:         "subpkg",
			Directory:       absPath("/subpkg"),
			File:            absPath("subpkg/subpkg_test.go"),
			Range: SourceRange{
				Start: SourcePosition{Line: 37, Column: 6},
				End:   SourcePosition{Line: 52, Column: 2},
			},
			SubTests: []*TestInfo{
				{
					Name:            "t1",
					DisplayName:     "t1",
					FullName:        "TestTable/t1",
					FullDisplayName: "TestTable/t1",
					Package:         "subpkg",
					Directory:       absPath("/subpkg"),
					File:            absPath("subpkg/subpkg_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 43, Column: 3},
						End:   SourcePosition{Line: 43, Column: 43},
					},
					HasGeneratedName: false,
					IsSubtest:        true,
				},
				{
					Name:            "t2",
					DisplayName:     "t2",
					FullName:        "TestTable/t2",
					FullDisplayName: "TestTable/t2",
					Package:         "subpkg",
					Directory:       absPath("/subpkg"),
					File:            absPath("subpkg/subpkg_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 44, Column: 3},
						End:   SourcePosition{Line: 44, Column: 43},
					},
					HasGeneratedName: false,
					IsSubtest:        true,
				},
			},
		},
		{
			Name:            "TestTableTestWithinSubTest",
			DisplayName:     "TestTableTestWithinSubTest",
			FullName:        "TestTableTestWithinSubTest",
			FullDisplayName: "TestTableTestWithinSubTest",
			Package:         "subpkg",
			Directory:       absPath("/subpkg"),
			File:            absPath("subpkg/subpkg_test.go"),
			Range: SourceRange{
				Start: SourcePosition{Line: 54, Column: 6},
				End:   SourcePosition{Line: 88, Column: 2},
			},
			SubTests: []*TestInfo{
				{
					Name:            "s1",
					DisplayName:     "s1",
					FullName:        "TestTableTestWithinSubTest/s1",
					FullDisplayName: "TestTableTestWithinSubTest/s1",
					Package:         "subpkg",
					Directory:       absPath("/subpkg"),
					File:            absPath("subpkg/subpkg_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 55, Column: 2},
						End:   SourcePosition{Line: 70, Column: 4},
					},
					IsSubtest: true,
					SubTests: []*TestInfo{
						{
							Name:            "t1",
							DisplayName:     "t1",
							FullName:        "TestTableTestWithinSubTest/s1/t1",
							FullDisplayName: "TestTableTestWithinSubTest/s1/t1",
							Package:         "subpkg",
							Directory:       absPath("/subpkg"),
							File:            absPath("subpkg/subpkg_test.go"),
							Range: SourceRange{
								Start: SourcePosition{Line: 61, Column: 4},
								End:   SourcePosition{Line: 61, Column: 44},
							},
							IsSubtest: true,
						},
						{
							Name:            "t2",
							DisplayName:     "t2",
							FullName:        "TestTableTestWithinSubTest/s1/t2",
							FullDisplayName: "TestTableTestWithinSubTest/s1/t2",
							Package:         "subpkg",
							Directory:       absPath("/subpkg"),
							File:            absPath("subpkg/subpkg_test.go"),
							Range: SourceRange{
								Start: SourcePosition{Line: 62, Column: 4},
								End:   SourcePosition{Line: 62, Column: 44},
							},
							IsSubtest: true,
						},
					},
				},
				{
					Name:            "s2",
					DisplayName:     "s2",
					FullName:        "TestTableTestWithinSubTest/s2",
					FullDisplayName: "TestTableTestWithinSubTest/s2",
					Package:         "subpkg",
					Directory:       absPath("/subpkg"),
					File:            absPath("subpkg/subpkg_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 72, Column: 2},
						End:   SourcePosition{Line: 87, Column: 4},
					},
					IsSubtest: true,
					SubTests: []*TestInfo{
						{
							Name:            "t1",
							DisplayName:     "t1",
							FullName:        "TestTableTestWithinSubTest/s2/t1",
							FullDisplayName: "TestTableTestWithinSubTest/s2/t1",
							Package:         "subpkg",
							Directory:       absPath("/subpkg"),
							File:            absPath("subpkg/subpkg_test.go"),
							Range: SourceRange{
								Start: SourcePosition{Line: 78, Column: 4},
								End:   SourcePosition{Line: 78, Column: 44},
							},
							IsSubtest: true,
						},
						{
							Name:            "t2",
							DisplayName:     "t2",
							FullName:        "TestTableTestWithinSubTest/s2/t2",
							FullDisplayName: "TestTableTestWithinSubTest/s2/t2",
							Package:         "subpkg",
							Directory:       absPath("/subpkg"),
							File:            absPath("subpkg/subpkg_test.go"),
							Range: SourceRange{
								Start: SourcePosition{Line: 79, Column: 4},
								End:   SourcePosition{Line: 79, Column: 44},
							},
							IsSubtest: true,
						},
					},
				},
			},
		},
		{
			Name:            "TestTableTestsWithinSubTestsWithPositionals",
			DisplayName:     "TestTableTestsWithinSubTestsWithPositionals",
			FullName:        "TestTableTestsWithinSubTestsWithPositionals",
			FullDisplayName: "TestTableTestsWithinSubTestsWithPositionals",
			Package:         "subpkg",
			Directory:       absPath("/subpkg"),
			File:            absPath("subpkg/subpkg_test.go"),
			Range: SourceRange{
				Start: SourcePosition{Line: 90, Column: 6},
				End:   SourcePosition{Line: 120, Column: 2},
			},
			SubTests: []*TestInfo{
				{
					Name:            "t1",
					DisplayName:     "t1",
					FullName:        "TestTableTestsWithinSubTestsWithPositionals/t1",
					FullDisplayName: "TestTableTestsWithinSubTestsWithPositionals/t1",
					Package:         "subpkg",
					Directory:       absPath("/subpkg"),
					File:            absPath("subpkg/subpkg_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 91, Column: 2},
						End:   SourcePosition{Line: 104, Column: 4},
					},
					IsSubtest: true,
					SubTests: []*TestInfo{
						{
							Name:            "tt1",
							DisplayName:     "tt1",
							FullName:        "TestTableTestsWithinSubTestsWithPositionals/t1/tt1",
							FullDisplayName: "TestTableTestsWithinSubTestsWithPositionals/t1/tt1",
							Package:         "subpkg",
							Directory:       absPath("/subpkg"),
							File:            absPath("subpkg/subpkg_test.go"),
							Range: SourceRange{
								Start: SourcePosition{Line: 96, Column: 4},
								End:   SourcePosition{Line: 96, Column: 18},
							},
							IsSubtest: true,
						},
						{
							Name:            "tt2 with space",
							DisplayName:     "tt2_with_space",
							FullName:        "TestTableTestsWithinSubTestsWithPositionals/t1/tt2 with space",
							FullDisplayName: "TestTableTestsWithinSubTestsWithPositionals/t1/tt2_with_space",
							Package:         "subpkg",
							Directory:       absPath("/subpkg"),
							File:            absPath("subpkg/subpkg_test.go"),
							Range: SourceRange{
								Start: SourcePosition{Line: 97, Column: 4},
								End:   SourcePosition{Line: 97, Column: 40},
							},
							IsSubtest: true,
						},
					},
				},
				{
					Name:            "t2",
					DisplayName:     "t2",
					FullName:        "TestTableTestsWithinSubTestsWithPositionals/t2",
					FullDisplayName: "TestTableTestsWithinSubTestsWithPositionals/t2",
					Package:         "subpkg",
					Directory:       absPath("/subpkg"),
					File:            absPath("subpkg/subpkg_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 106, Column: 2},
						End:   SourcePosition{Line: 119, Column: 4},
					},
					IsSubtest: true,
					SubTests: []*TestInfo{
						{
							Name:            "tt1",
							DisplayName:     "tt1",
							FullName:        "TestTableTestsWithinSubTestsWithPositionals/t2/tt1",
							FullDisplayName: "TestTableTestsWithinSubTestsWithPositionals/t2/tt1",
							Package:         "subpkg",
							Directory:       absPath("/subpkg"),
							File:            absPath("subpkg/subpkg_test.go"),
							Range: SourceRange{
								Start: SourcePosition{Line: 111, Column: 4},
								End:   SourcePosition{Line: 111, Column: 18},
							},
							IsSubtest: true,
						},
						{
							Name:            "tt2 with space",
							DisplayName:     "tt2_with_space",
							FullName:        "TestTableTestsWithinSubTestsWithPositionals/t2/tt2 with space",
							FullDisplayName: "TestTableTestsWithinSubTestsWithPositionals/t2/tt2_with_space",
							Package:         "subpkg",
							Directory:       absPath("/subpkg"),
							File:            absPath("subpkg/subpkg_test.go"),
							Range: SourceRange{
								Start: SourcePosition{Line: 112, Column: 4},
								End:   SourcePosition{Line: 112, Column: 40},
							},
							IsSubtest: true,
						},
					},
				},
			},
		},
		{
			Name:            "TestSimple",
			DisplayName:     "TestSimple",
			FullName:        "TestSimple",
			FullDisplayName: "TestSimple",
			Package:         "subpkg/pkg1",
			Directory:       absPath("/subpkg/pkg1"),
			File:            absPath("/subpkg/pkg1/pkg_test.go"),
			Range: SourceRange{
				Start: SourcePosition{Line: 8, Column: 6},
				End:   SourcePosition{Line: 10, Column: 2},
			},
		},
		{
			Name:            "TestSubTests",
			DisplayName:     "TestSubTests",
			FullName:        "TestSubTests",
			FullDisplayName: "TestSubTests",
			Package:         "subpkg/pkg1",
			Directory:       absPath("/subpkg/pkg1"),
			File:            absPath("/subpkg/pkg1/pkg_test.go"),
			Range: SourceRange{
				Start: SourcePosition{Line: 12, Column: 6},
				End:   SourcePosition{Line: 19, Column: 2},
			},
			SubTests: []*TestInfo{
				{
					Name:            "t1",
					DisplayName:     "t1",
					FullName:        "TestSubTests/t1",
					FullDisplayName: "TestSubTests/t1",
					Package:         "subpkg/pkg1",
					Directory:       absPath("/subpkg/pkg1"),
					File:            absPath("/subpkg/pkg1/pkg_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 13, Column: 2},
						End:   SourcePosition{Line: 15, Column: 4},
					},
					IsSubtest: true,
				},
				{
					Name:            "t2",
					DisplayName:     "t2",
					FullName:        "TestSubTests/t2",
					FullDisplayName: "TestSubTests/t2",
					Package:         "subpkg/pkg1",
					Directory:       absPath("/subpkg/pkg1"),
					File:            absPath("/subpkg/pkg1/pkg_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 16, Column: 2},
						End:   SourcePosition{Line: 18, Column: 4},
					},
					IsSubtest: true,
				},
			},
		},
		{
			Name:            "TestNestedSubTests",
			DisplayName:     "TestNestedSubTests",
			FullName:        "TestNestedSubTests",
			FullDisplayName: "TestNestedSubTests",
			Package:         "subpkg/pkg1",
			Directory:       absPath("/subpkg/pkg1"),
			File:            absPath("/subpkg/pkg1/pkg_test.go"),
			Range: SourceRange{
				Start: SourcePosition{Line: 21, Column: 6},
				End:   SourcePosition{Line: 27, Column: 2},
			},
			SubTests: []*TestInfo{{
				Name:            "t1",
				DisplayName:     "t1",
				FullName:        "TestNestedSubTests/t1",
				FullDisplayName: "TestNestedSubTests/t1",
				Package:         "subpkg/pkg1",
				Directory:       absPath("/subpkg/pkg1"),
				File:            absPath("/subpkg/pkg1/pkg_test.go"),
				Range: SourceRange{
					Start: SourcePosition{Line: 22, Column: 2},
					End:   SourcePosition{Line: 26, Column: 4},
				},
				IsSubtest: true,
				SubTests: []*TestInfo{{
					Name:            "t1",
					DisplayName:     "t1",
					FullName:        "TestNestedSubTests/t1/t1",
					FullDisplayName: "TestNestedSubTests/t1/t1",
					Package:         "subpkg/pkg1",
					Directory:       absPath("/subpkg/pkg1"),
					File:            absPath("/subpkg/pkg1/pkg_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 23, Column: 3},
						End:   SourcePosition{Line: 25, Column: 5},
					},
					IsSubtest: true,
				}},
			}},
		},
		{
			Name:            "TestSubTestsWithGeneratedNames",
			DisplayName:     "TestSubTestsWithGeneratedNames",
			FullName:        "TestSubTestsWithGeneratedNames",
			FullDisplayName: "TestSubTestsWithGeneratedNames",
			Package:         "subpkg/pkg1",
			Directory:       absPath("/subpkg/pkg1"),
			File:            absPath("/subpkg/pkg1/pkg_test.go"),
			Range: SourceRange{
				Start: SourcePosition{Line: 29, Column: 6},
				End:   SourcePosition{Line: 35, Column: 2},
			},
			SubTests: []*TestInfo{{
				Name:            `<fmt.Sprintf("t%v", i)>`,
				DisplayName:     `<fmt.Sprintf("t%v", i)>`,
				FullName:        `TestSubTestsWithGeneratedNames/<fmt.Sprintf("t%v", i)>`,
				FullDisplayName: `TestSubTestsWithGeneratedNames/<fmt.Sprintf("t%v", i)>`,
				Package:         "subpkg/pkg1",
				Directory:       absPath("/subpkg/pkg1"),
				File:            absPath("/subpkg/pkg1/pkg_test.go"),
				Range: SourceRange{
					Start: SourcePosition{Line: 31, Column: 3},
					End:   SourcePosition{Line: 33, Column: 5},
				},
				HasGeneratedName: true,
				IsSubtest:        true,
			}},
		},
		{
			Name:            "TestTable",
			DisplayName:     "TestTable",
			FullName:        "TestTable",
			FullDisplayName: "TestTable",
			Package:         "subpkg/pkg1",
			Directory:       absPath("/subpkg/pkg1"),
			File:            absPath("/subpkg/pkg1/pkg_test.go"),
			Range: SourceRange{
				Start: SourcePosition{Line: 37, Column: 6},
				End:   SourcePosition{Line: 52, Column: 2},
			},
			SubTests: []*TestInfo{
				{
					Name:            "t1",
					DisplayName:     "t1",
					FullName:        "TestTable/t1",
					FullDisplayName: "TestTable/t1",
					Package:         "subpkg/pkg1",
					Directory:       absPath("/subpkg/pkg1"),
					File:            absPath("/subpkg/pkg1/pkg_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 43, Column: 3},
						End:   SourcePosition{Line: 43, Column: 43},
					},
					HasGeneratedName: false,
					IsSubtest:        true,
				},
				{
					Name:            "t2",
					DisplayName:     "t2",
					FullName:        "TestTable/t2",
					FullDisplayName: "TestTable/t2",
					Package:         "subpkg/pkg1",
					Directory:       absPath("/subpkg/pkg1"),
					File:            absPath("/subpkg/pkg1/pkg_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 44, Column: 3},
						End:   SourcePosition{Line: 44, Column: 43},
					},
					HasGeneratedName: false,
					IsSubtest:        true,
				},
			},
		},
		{
			Name:            "TestTableTestWithinSubTest",
			DisplayName:     "TestTableTestWithinSubTest",
			FullName:        "TestTableTestWithinSubTest",
			FullDisplayName: "TestTableTestWithinSubTest",
			Package:         "subpkg/pkg1",
			Directory:       absPath("/subpkg/pkg1"),
			File:            absPath("/subpkg/pkg1/pkg_test.go"),
			Range: SourceRange{
				Start: SourcePosition{Line: 54, Column: 6},
				End:   SourcePosition{Line: 88, Column: 2},
			},
			SubTests: []*TestInfo{
				{
					Name:            "s1",
					DisplayName:     "s1",
					FullName:        "TestTableTestWithinSubTest/s1",
					FullDisplayName: "TestTableTestWithinSubTest/s1",
					Package:         "subpkg/pkg1",
					Directory:       absPath("/subpkg/pkg1"),
					File:            absPath("/subpkg/pkg1/pkg_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 55, Column: 2},
						End:   SourcePosition{Line: 70, Column: 4},
					},
					IsSubtest: true,
					SubTests: []*TestInfo{
						{
							Name:            "t1",
							DisplayName:     "t1",
							FullName:        "TestTableTestWithinSubTest/s1/t1",
							FullDisplayName: "TestTableTestWithinSubTest/s1/t1",
							Package:         "subpkg/pkg1",
							Directory:       absPath("/subpkg/pkg1"),
							File:            absPath("/subpkg/pkg1/pkg_test.go"),
							Range: SourceRange{
								Start: SourcePosition{Line: 61, Column: 4},
								End:   SourcePosition{Line: 61, Column: 44},
							},
							IsSubtest: true,
						},
						{
							Name:            "t2",
							DisplayName:     "t2",
							FullName:        "TestTableTestWithinSubTest/s1/t2",
							FullDisplayName: "TestTableTestWithinSubTest/s1/t2",
							Package:         "subpkg/pkg1",
							Directory:       absPath("/subpkg/pkg1"),
							File:            absPath("/subpkg/pkg1/pkg_test.go"),
							Range: SourceRange{
								Start: SourcePosition{Line: 62, Column: 4},
								End:   SourcePosition{Line: 62, Column: 44},
							},
							IsSubtest: true,
						},
					},
				},
				{
					Name:            "s2",
					DisplayName:     "s2",
					FullName:        "TestTableTestWithinSubTest/s2",
					FullDisplayName: "TestTableTestWithinSubTest/s2",
					Package:         "subpkg/pkg1",
					Directory:       absPath("/subpkg/pkg1"),
					File:            absPath("/subpkg/pkg1/pkg_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 72, Column: 2},
						End:   SourcePosition{Line: 87, Column: 4},
					},
					IsSubtest: true,
					SubTests: []*TestInfo{
						{
							Name:            "t1",
							DisplayName:     "t1",
							FullName:        "TestTableTestWithinSubTest/s2/t1",
							FullDisplayName: "TestTableTestWithinSubTest/s2/t1",
							Package:         "subpkg/pkg1",
							Directory:       absPath("/subpkg/pkg1"),
							File:            absPath("/subpkg/pkg1/pkg_test.go"),
							Range: SourceRange{
								Start: SourcePosition{Line: 78, Column: 4},
								End:   SourcePosition{Line: 78, Column: 44},
							},
							IsSubtest: true,
						},
						{
							Name:            "t2",
							DisplayName:     "t2",
							FullName:        "TestTableTestWithinSubTest/s2/t2",
							FullDisplayName: "TestTableTestWithinSubTest/s2/t2",
							Package:         "subpkg/pkg1",
							Directory:       absPath("/subpkg/pkg1"),
							File:            absPath("/subpkg/pkg1/pkg_test.go"),
							Range: SourceRange{
								Start: SourcePosition{Line: 79, Column: 4},
								End:   SourcePosition{Line: 79, Column: 44},
							},
							IsSubtest: true,
						},
					},
				},
			},
		},
		{
			Name:            "TestTableTestsWithinSubTestsWithPositionals",
			DisplayName:     "TestTableTestsWithinSubTestsWithPositionals",
			FullName:        "TestTableTestsWithinSubTestsWithPositionals",
			FullDisplayName: "TestTableTestsWithinSubTestsWithPositionals",
			Package:         "subpkg/pkg1",
			Directory:       absPath("/subpkg/pkg1"),
			File:            absPath("/subpkg/pkg1/pkg_test.go"),
			Range: SourceRange{
				Start: SourcePosition{Line: 90, Column: 6},
				End:   SourcePosition{Line: 120, Column: 2},
			},
			SubTests: []*TestInfo{
				{
					Name:            "t1",
					DisplayName:     "t1",
					FullName:        "TestTableTestsWithinSubTestsWithPositionals/t1",
					FullDisplayName: "TestTableTestsWithinSubTestsWithPositionals/t1",
					Package:         "subpkg/pkg1",
					Directory:       absPath("/subpkg/pkg1"),
					File:            absPath("/subpkg/pkg1/pkg_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 91, Column: 2},
						End:   SourcePosition{Line: 104, Column: 4},
					},
					IsSubtest: true,
					SubTests: []*TestInfo{
						{
							Name:            "tt1",
							DisplayName:     "tt1",
							FullName:        "TestTableTestsWithinSubTestsWithPositionals/t1/tt1",
							FullDisplayName: "TestTableTestsWithinSubTestsWithPositionals/t1/tt1",
							Package:         "subpkg/pkg1",
							Directory:       absPath("/subpkg/pkg1"),
							File:            absPath("/subpkg/pkg1/pkg_test.go"),
							Range: SourceRange{
								Start: SourcePosition{Line: 96, Column: 4},
								End:   SourcePosition{Line: 96, Column: 18},
							},
							IsSubtest: true,
						},
						{
							Name:            "tt2 with space",
							DisplayName:     "tt2_with_space",
							FullName:        "TestTableTestsWithinSubTestsWithPositionals/t1/tt2 with space",
							FullDisplayName: "TestTableTestsWithinSubTestsWithPositionals/t1/tt2_with_space",
							Package:         "subpkg/pkg1",
							Directory:       absPath("/subpkg/pkg1"),
							File:            absPath("/subpkg/pkg1/pkg_test.go"),
							Range: SourceRange{
								Start: SourcePosition{Line: 97, Column: 4},
								End:   SourcePosition{Line: 97, Column: 40},
							},
							IsSubtest: true,
						},
					},
				},
				{
					Name:            "t2",
					DisplayName:     "t2",
					FullName:        "TestTableTestsWithinSubTestsWithPositionals/t2",
					FullDisplayName: "TestTableTestsWithinSubTestsWithPositionals/t2",
					Package:         "subpkg/pkg1",
					Directory:       absPath("/subpkg/pkg1"),
					File:            absPath("/subpkg/pkg1/pkg_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 106, Column: 2},
						End:   SourcePosition{Line: 119, Column: 4},
					},
					IsSubtest: true,
					SubTests: []*TestInfo{
						{
							Name:            "tt1",
							DisplayName:     "tt1",
							FullName:        "TestTableTestsWithinSubTestsWithPositionals/t2/tt1",
							FullDisplayName: "TestTableTestsWithinSubTestsWithPositionals/t2/tt1",
							Package:         "subpkg/pkg1",
							Directory:       absPath("/subpkg/pkg1"),
							File:            absPath("/subpkg/pkg1/pkg_test.go"),
							Range: SourceRange{
								Start: SourcePosition{Line: 111, Column: 4},
								End:   SourcePosition{Line: 111, Column: 18},
							},
							IsSubtest: true,
						},
						{
							Name:            "tt2 with space",
							DisplayName:     "tt2_with_space",
							FullName:        "TestTableTestsWithinSubTestsWithPositionals/t2/tt2 with space",
							FullDisplayName: "TestTableTestsWithinSubTestsWithPositionals/t2/tt2_with_space",
							Package:         "subpkg/pkg1",
							Directory:       absPath("/subpkg/pkg1"),
							File:            absPath("/subpkg/pkg1/pkg_test.go"),
							Range: SourceRange{
								Start: SourcePosition{Line: 112, Column: 4},
								End:   SourcePosition{Line: 112, Column: 40},
							},
							IsSubtest: true,
						},
					},
				},
			},
		},
		{
			Name:            "TestSimple",
			DisplayName:     "TestSimple",
			FullName:        "TestSimple",
			FullDisplayName: "TestSimple",
			Package:         "subpkg/pkg2",
			Directory:       absPath("/subpkg/pkg2"),
			File:            absPath("/subpkg/pkg2/pkg_test.go"),
			Range: SourceRange{
				Start: SourcePosition{Line: 8, Column: 6},
				End:   SourcePosition{Line: 10, Column: 2},
			},
		},
		{
			Name:            "TestSubTests",
			DisplayName:     "TestSubTests",
			FullName:        "TestSubTests",
			FullDisplayName: "TestSubTests",
			Package:         "subpkg/pkg2",
			Directory:       absPath("/subpkg/pkg2"),
			File:            absPath("/subpkg/pkg2/pkg_test.go"),
			Range: SourceRange{
				Start: SourcePosition{Line: 12, Column: 6},
				End:   SourcePosition{Line: 19, Column: 2},
			},
			SubTests: []*TestInfo{
				{
					Name:            "t1",
					DisplayName:     "t1",
					FullName:        "TestSubTests/t1",
					FullDisplayName: "TestSubTests/t1",
					Package:         "subpkg/pkg2",
					Directory:       absPath("/subpkg/pkg2"),
					File:            absPath("/subpkg/pkg2/pkg_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 13, Column: 2},
						End:   SourcePosition{Line: 15, Column: 4},
					},
					IsSubtest: true,
				},
				{
					Name:            "t2",
					DisplayName:     "t2",
					FullName:        "TestSubTests/t2",
					FullDisplayName: "TestSubTests/t2",
					Package:         "subpkg/pkg2",
					Directory:       absPath("/subpkg/pkg2"),
					File:            absPath("/subpkg/pkg2/pkg_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 16, Column: 2},
						End:   SourcePosition{Line: 18, Column: 4},
					},
					IsSubtest: true,
				},
			},
		},
		{
			Name:            "TestNestedSubTests",
			DisplayName:     "TestNestedSubTests",
			FullName:        "TestNestedSubTests",
			FullDisplayName: "TestNestedSubTests",
			Package:         "subpkg/pkg2",
			Directory:       absPath("/subpkg/pkg2"),
			File:            absPath("/subpkg/pkg2/pkg_test.go"),
			Range: SourceRange{
				Start: SourcePosition{Line: 21, Column: 6},
				End:   SourcePosition{Line: 27, Column: 2},
			},
			SubTests: []*TestInfo{{
				Name:            "t1",
				DisplayName:     "t1",
				FullName:        "TestNestedSubTests/t1",
				FullDisplayName: "TestNestedSubTests/t1",
				Package:         "subpkg/pkg2",
				Directory:       absPath("/subpkg/pkg2"),
				File:            absPath("/subpkg/pkg2/pkg_test.go"),
				Range: SourceRange{
					Start: SourcePosition{Line: 22, Column: 2},
					End:   SourcePosition{Line: 26, Column: 4},
				},
				IsSubtest: true,
				SubTests: []*TestInfo{{
					Name:            "t1",
					DisplayName:     "t1",
					FullName:        "TestNestedSubTests/t1/t1",
					FullDisplayName: "TestNestedSubTests/t1/t1",
					Package:         "subpkg/pkg2",
					Directory:       absPath("/subpkg/pkg2"),
					File:            absPath("/subpkg/pkg2/pkg_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 23, Column: 3},
						End:   SourcePosition{Line: 25, Column: 5},
					},
					IsSubtest: true,
				}},
			}},
		},
		{
			Name:            "TestSubTestsWithGeneratedNames",
			DisplayName:     "TestSubTestsWithGeneratedNames",
			FullName:        "TestSubTestsWithGeneratedNames",
			FullDisplayName: "TestSubTestsWithGeneratedNames",
			Package:         "subpkg/pkg2",
			Directory:       absPath("/subpkg/pkg2"),
			File:            absPath("/subpkg/pkg2/pkg_test.go"),
			Range: SourceRange{
				Start: SourcePosition{Line: 29, Column: 6},
				End:   SourcePosition{Line: 35, Column: 2},
			},
			SubTests: []*TestInfo{{
				Name:            `<fmt.Sprintf("t%v", i)>`,
				DisplayName:     `<fmt.Sprintf("t%v", i)>`,
				FullName:        `TestSubTestsWithGeneratedNames/<fmt.Sprintf("t%v", i)>`,
				FullDisplayName: `TestSubTestsWithGeneratedNames/<fmt.Sprintf("t%v", i)>`,
				Package:         "subpkg/pkg2",
				Directory:       absPath("/subpkg/pkg2"),
				File:            absPath("/subpkg/pkg2/pkg_test.go"),
				Range: SourceRange{
					Start: SourcePosition{Line: 31, Column: 3},
					End:   SourcePosition{Line: 33, Column: 5},
				},
				HasGeneratedName: true,
				IsSubtest:        true,
			}},
		},
		{
			Name:            "TestTable",
			DisplayName:     "TestTable",
			FullName:        "TestTable",
			FullDisplayName: "TestTable",
			Package:         "subpkg/pkg2",
			Directory:       absPath("/subpkg/pkg2"),
			File:            absPath("/subpkg/pkg2/pkg_test.go"),
			Range: SourceRange{
				Start: SourcePosition{Line: 37, Column: 6},
				End:   SourcePosition{Line: 52, Column: 2},
			},
			SubTests: []*TestInfo{
				{
					Name:            "t1",
					DisplayName:     "t1",
					FullName:        "TestTable/t1",
					FullDisplayName: "TestTable/t1",
					Package:         "subpkg/pkg2",
					Directory:       absPath("/subpkg/pkg2"),
					File:            absPath("/subpkg/pkg2/pkg_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 43, Column: 3},
						End:   SourcePosition{Line: 43, Column: 43},
					},
					HasGeneratedName: false,
					IsSubtest:        true,
				},
				{
					Name:            "t2",
					DisplayName:     "t2",
					FullName:        "TestTable/t2",
					FullDisplayName: "TestTable/t2",
					Package:         "subpkg/pkg2",
					Directory:       absPath("/subpkg/pkg2"),
					File:            absPath("/subpkg/pkg2/pkg_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 44, Column: 3},
						End:   SourcePosition{Line: 44, Column: 43},
					},
					HasGeneratedName: false,
					IsSubtest:        true,
				},
			},
		},
		{
			Name:            "TestTableTestWithinSubTest",
			DisplayName:     "TestTableTestWithinSubTest",
			FullName:        "TestTableTestWithinSubTest",
			FullDisplayName: "TestTableTestWithinSubTest",
			Package:         "subpkg/pkg2",
			Directory:       absPath("/subpkg/pkg2"),
			File:            absPath("/subpkg/pkg2/pkg_test.go"),
			Range: SourceRange{
				Start: SourcePosition{Line: 54, Column: 6},
				End:   SourcePosition{Line: 88, Column: 2},
			},
			SubTests: []*TestInfo{
				{
					Name:            "s1",
					DisplayName:     "s1",
					FullName:        "TestTableTestWithinSubTest/s1",
					FullDisplayName: "TestTableTestWithinSubTest/s1",
					Package:         "subpkg/pkg2",
					Directory:       absPath("/subpkg/pkg2"),
					File:            absPath("/subpkg/pkg2/pkg_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 55, Column: 2},
						End:   SourcePosition{Line: 70, Column: 4},
					},
					IsSubtest: true,
					SubTests: []*TestInfo{
						{
							Name:            "t1",
							DisplayName:     "t1",
							FullName:        "TestTableTestWithinSubTest/s1/t1",
							FullDisplayName: "TestTableTestWithinSubTest/s1/t1",
							Package:         "subpkg/pkg2",
							Directory:       absPath("/subpkg/pkg2"),
							File:            absPath("/subpkg/pkg2/pkg_test.go"),
							Range: SourceRange{
								Start: SourcePosition{Line: 61, Column: 4},
								End:   SourcePosition{Line: 61, Column: 44},
							},
							IsSubtest: true,
						},
						{
							Name:            "t2",
							DisplayName:     "t2",
							FullName:        "TestTableTestWithinSubTest/s1/t2",
							FullDisplayName: "TestTableTestWithinSubTest/s1/t2",
							Package:         "subpkg/pkg2",
							Directory:       absPath("/subpkg/pkg2"),
							File:            absPath("/subpkg/pkg2/pkg_test.go"),
							Range: SourceRange{
								Start: SourcePosition{Line: 62, Column: 4},
								End:   SourcePosition{Line: 62, Column: 44},
							},
							IsSubtest: true,
						},
					},
				},
				{
					Name:            "s2",
					DisplayName:     "s2",
					FullName:        "TestTableTestWithinSubTest/s2",
					FullDisplayName: "TestTableTestWithinSubTest/s2",
					Package:         "subpkg/pkg2",
					Directory:       absPath("/subpkg/pkg2"),
					File:            absPath("/subpkg/pkg2/pkg_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 72, Column: 2},
						End:   SourcePosition{Line: 87, Column: 4},
					},
					IsSubtest: true,
					SubTests: []*TestInfo{
						{
							Name:            "t1",
							DisplayName:     "t1",
							FullName:        "TestTableTestWithinSubTest/s2/t1",
							FullDisplayName: "TestTableTestWithinSubTest/s2/t1",
							Package:         "subpkg/pkg2",
							Directory:       absPath("/subpkg/pkg2"),
							File:            absPath("/subpkg/pkg2/pkg_test.go"),
							Range: SourceRange{
								Start: SourcePosition{Line: 78, Column: 4},
								End:   SourcePosition{Line: 78, Column: 44},
							},
							IsSubtest: true,
						},
						{
							Name:            "t2",
							DisplayName:     "t2",
							FullName:        "TestTableTestWithinSubTest/s2/t2",
							FullDisplayName: "TestTableTestWithinSubTest/s2/t2",
							Package:         "subpkg/pkg2",
							Directory:       absPath("/subpkg/pkg2"),
							File:            absPath("/subpkg/pkg2/pkg_test.go"),
							Range: SourceRange{
								Start: SourcePosition{Line: 79, Column: 4},
								End:   SourcePosition{Line: 79, Column: 44},
							},
							IsSubtest: true,
						},
					},
				},
			},
		},
		{
			Name:            "TestTableTestsWithinSubTestsWithPositionals",
			DisplayName:     "TestTableTestsWithinSubTestsWithPositionals",
			FullName:        "TestTableTestsWithinSubTestsWithPositionals",
			FullDisplayName: "TestTableTestsWithinSubTestsWithPositionals",
			Package:         "subpkg/pkg2",
			Directory:       absPath("/subpkg/pkg2"),
			File:            absPath("/subpkg/pkg2/pkg_test.go"),
			Range: SourceRange{
				Start: SourcePosition{Line: 90, Column: 6},
				End:   SourcePosition{Line: 120, Column: 2},
			},
			SubTests: []*TestInfo{
				{
					Name:            "t1",
					DisplayName:     "t1",
					FullName:        "TestTableTestsWithinSubTestsWithPositionals/t1",
					FullDisplayName: "TestTableTestsWithinSubTestsWithPositionals/t1",
					Package:         "subpkg/pkg2",
					Directory:       absPath("/subpkg/pkg2"),
					File:            absPath("/subpkg/pkg2/pkg_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 91, Column: 2},
						End:   SourcePosition{Line: 104, Column: 4},
					},
					IsSubtest: true,
					SubTests: []*TestInfo{
						{
							Name:            "tt1",
							DisplayName:     "tt1",
							FullName:        "TestTableTestsWithinSubTestsWithPositionals/t1/tt1",
							FullDisplayName: "TestTableTestsWithinSubTestsWithPositionals/t1/tt1",
							Package:         "subpkg/pkg2",
							Directory:       absPath("/subpkg/pkg2"),
							File:            absPath("/subpkg/pkg2/pkg_test.go"),
							Range: SourceRange{
								Start: SourcePosition{Line: 96, Column: 4},
								End:   SourcePosition{Line: 96, Column: 18},
							},
							IsSubtest: true,
						},
						{
							Name:            "tt2 with space",
							DisplayName:     "tt2_with_space",
							FullName:        "TestTableTestsWithinSubTestsWithPositionals/t1/tt2 with space",
							FullDisplayName: "TestTableTestsWithinSubTestsWithPositionals/t1/tt2_with_space",
							Package:         "subpkg/pkg2",
							Directory:       absPath("/subpkg/pkg2"),
							File:            absPath("/subpkg/pkg2/pkg_test.go"),
							Range: SourceRange{
								Start: SourcePosition{Line: 97, Column: 4},
								End:   SourcePosition{Line: 97, Column: 40},
							},
							IsSubtest: true,
						},
					},
				},
				{
					Name:            "t2",
					DisplayName:     "t2",
					FullName:        "TestTableTestsWithinSubTestsWithPositionals/t2",
					FullDisplayName: "TestTableTestsWithinSubTestsWithPositionals/t2",
					Package:         "subpkg/pkg2",
					Directory:       absPath("/subpkg/pkg2"),
					File:            absPath("/subpkg/pkg2/pkg_test.go"),
					Range: SourceRange{
						Start: SourcePosition{Line: 106, Column: 2},
						End:   SourcePosition{Line: 119, Column: 4},
					},
					IsSubtest: true,
					SubTests: []*TestInfo{
						{
							Name:            "tt1",
							DisplayName:     "tt1",
							FullName:        "TestTableTestsWithinSubTestsWithPositionals/t2/tt1",
							FullDisplayName: "TestTableTestsWithinSubTestsWithPositionals/t2/tt1",
							Package:         "subpkg/pkg2",
							Directory:       absPath("/subpkg/pkg2"),
							File:            absPath("/subpkg/pkg2/pkg_test.go"),
							Range: SourceRange{
								Start: SourcePosition{Line: 111, Column: 4},
								End:   SourcePosition{Line: 111, Column: 18},
							},
							IsSubtest: true,
						},
						{
							Name:            "tt2 with space",
							DisplayName:     "tt2_with_space",
							FullName:        "TestTableTestsWithinSubTestsWithPositionals/t2/tt2 with space",
							FullDisplayName: "TestTableTestsWithinSubTestsWithPositionals/t2/tt2_with_space",
							Package:         "subpkg/pkg2",
							Directory:       absPath("/subpkg/pkg2"),
							File:            absPath("/subpkg/pkg2/pkg_test.go"),
							Range: SourceRange{
								Start: SourcePosition{Line: 112, Column: 4},
								End:   SourcePosition{Line: 112, Column: 40},
							},
							IsSubtest: true,
						},
					},
				},
			},
		},
	}
	if diff := cmp.Diff(want, got, testInfoCmpOpts()); diff != "" {
		t.Errorf("mismatch (-want +got):\n%s", diff)
	}
}

func testInfoCmpOpts() cmp.Option {
	return cmp.Options{
		cmpopts.SortSlices(func(a, b *TestInfo) bool {
			return a.FullName < b.FullName
		}),
	}
}
