name: feneradam-slack
on:
  schedule:
    - cron: '00 12 * * 1-5'
  workflow_dispatch:
    inputs:
      feneradam_args:
        required: false
        default: '-all'
        description: Arguments to pass 'feneradam'
jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install feneradam
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.3'
    - run:  go install ./feneradam

    - name: Install slack-send
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.3'
    - run:  go install ./slack-send

    - name: Feneradam
      id: feneradam
      env:
        DEFAULT_ARGS: ''
      run: |
        output=$(feneradam ${{  github.event.inputs.feneradam_args || env.DEFAULT_ARGS }})
        output="${output//'%'/'%25'}"
        output="${output//$'\n'/'%0A'}"
        output="${output//$'\r'/'%0D'}"
        echo "::set-output name=message::${output}"
    - name: Test Output
      run: |
        echo "${{ steps.feneradam.outputs.message}}"

    - name: Ping Slack
      if: ${{ steps.feneradam.outputs.message != '' }}
      run: |
        echo "${{ steps.feneradam.outputs.message }}" | slack-send
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
