name: feneradam-slack
on:
  schedule:
    - cron: '00 12 * * *'
jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.3'
    - run:  go install ./feneradam

    - name: Feneradam
      # run: echo "test"
      id: feneradam
      run: |
        output=$(feneradam)
        output="${output//'%'/'%25'}"
        output="${output//$'\n'/'%0A'}"
        output="${output//$'\r'/'%0D'}"
        echo "::set-output name=message::${output}"
    - name: Test Output
      run: |
        echo "${{ steps.feneradam.outputs.message}}"

    - name: Ping Slack
      if: ${{ steps.feneradam.outputs.message != '' }}
      uses: abinoda/slack-action@v1.0.7
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      with:
        args: |
          '{
              "text": "Feneradam Traffic Report",
              "blocks": [
                  {
                      "type": "section",
                      "text": {
                          "type": "mrkdwn",
                          "text": "${{ steps.feneradam.outputs.message}}"
                      }
                  }
              ],
              "channel" : "${{ secrets.SLACK_CHANNEL_ID }}"
          }'

